name: "Hyperion"
version: "latest"
slug: "hyperion"
description: "Hyperion NG via image GHCR (mode host, ingress, devices USB/vidéo/série)"
url: "https://github.com/tbringuier/homeassistant-addons/tree/main/hyperion"
arch:
  - amd64
  - aarch64
  - armv7

startup: "application"

host_network: true
apparmor: false

watchdog: "tcp://[HOST]:[PORT:8090]"

usb: true
uart: true
video: true
udev: true

map:
  - type: addon_config
    read_only: false
    path: /config

image: "ghcr.io/tbringuier/hyperionng-dockerized"
